name: Shell Commands

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # step 0 
      - name: Checkout
        uses: actions/checkout@v1
      - id: set-matrix
        run: |
          content=`cat $GITHUB_WORKSPACE/settings.json`
          echo "::set-output name=matrix::$content"
          echo $content
          echo "**************************"
          echo steps.job1.outputs.matrix
          echo "**************************"
          echo "--------------------------"
          echo $matrix | jq '.'
          echo "--------------------------"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set output
      id: set
      run: |
        echo ::set-output name=json_var::'[{ "name": "test", "client_payload": "111" }, { "name": "test2", "client_payload": "222" }] '
    - name: use output
      run: |
        echo $json_var | jq '.[].name'
      env:
        json_var: ${{ steps.set.outputs.json_var}}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{fromJson(needs.job1.outputs.matrix)}}"