name: Shell Commands

on: [push]

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      # step 0 
      - name: Checkout
        uses: actions/checkout@v1
  
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        content=`cat $GITHUB_WORKSPACE/settings.json`
        echo "::set-output name=matrix::$content"
        echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{fromJson(needs.job1.outputs.matrix).version}}"