name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: echo a string
        run: echo "Hello World Actions!"
      
      # step 2
      - name: multiline script
        run: |
          node -v
          npm -v
      - id: set_var
        run: |
          content=`cat $GITHUB_WORKSPACE/settings.json`
          echo "::set-output name=settingsJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.settingsJson).version}}"