name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      # step 0 
      - name: Checkout
        uses: actions/checkout@v1
      # step 1
      - name: echo a string
        run: echo "Hello World Actions!"
      
      # step 2
      - name: multiline script
        run: |
          node -v
          npm -v
      - id: set_var
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          ls -la
          cat $GITHUB_WORKSPACE/settings.json
          content=`cat $GITHUB_WORKSPACE/settings.json`
          echo "::set-output name=jsonValue::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.jsonValue).version}}"